apiVersion: v1
kind: PersistentVolume
metadata:
  name: ecommerce-db-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/ecommerce-db
    type: DirectoryOrCreate