apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: prod
resources:
  - ../../base
  - namespace.yaml
  - resource-quota.yaml
images:
  - name: pabloher95/ecommerce-database
    newTag: latest
  - name: pabloher95/ecommerce-product-service
    newTag: latest
  - name: pabloher95/ecommerce-order-service
    newTag: latest
  - name: pabloher95/ecommerce-frontend
    newTag: latest