apiVersion: v1
kind: ConfigMap
metadata:
  name: ecommerce-order-service-config
data:
  PORT: "3002"
  DB_HOST: ecommerce-database
  DB_NAME: ecommerce
  PRODUCT_SERVICE_URL: http://ecommerce-product-service:3001