apiVersion: v1
kind: Service
metadata:
  name: ecommerce-order-service
spec:
  type: ClusterIP
  selector:
    app: ecommerce-order-service
  ports:
    - port: 3002
      targetPort: 3002
      name: http