apiVersion: v1
kind: Service
metadata:
  name: ecommerce-product-service
spec:
  type: ClusterIP
  selector:
    app: ecommerce-product-service
  ports:
    - port: 3001
      targetPort: 3001
      name: http