apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - database/deployment.yaml
  - database/service-clusterip.yaml
  - database/configmap.yaml
  - database/secret.yaml
  - database/pvc.yaml
  - database/pv.yaml
  - product-service/deployment.yaml
  - product-service/service-clusterip.yaml
  - product-service/service-nodeport.yaml
  - product-service/configmap.yaml
  - product-service/secret.yaml
  - order-service/deployment.yaml
  - order-service/service-clusterip.yaml
  - order-service/service-nodeport.yaml
  - order-service/configmap.yaml
  - order-service/secret.yaml
  - frontend/deployment.yaml
  - frontend/service-clusterip.yaml
  - frontend/service-nodeport.yaml
  - frontend/configmap.yaml
commonLabels:
  app.kubernetes.io/part-of: ecommerce